### ISSUE TITLE
Adding some API visibility

### ISSUE THREAD

**Issue by tacurran** [ory/ory-config#1]
In the Ory Community there are often questions relating to the API calls. A visualisation of the API interactions, as documented in the Swagger/Open Api generated spec could improve an understanding for the various assets. The scope would follow along methods defined for instance:
 "http_method": { "type": "string",
      "enum": [ "POST", "GET", "PUT", "PATCH", "DELETE", "CONNECT", "HEAD", "OPTIONS", "TRACE" ] }

Example
GET /.well-known/jwks.json HTTP/1.1

Some information would include:
- Headers, list
- Responses , maybe as tabs or buttons 
| 200 | OK | JSONWebKeySet | JSONWebKeySet
| 500 | Internal Server Error | genericError | genericError
- Body, list, if applicable
- Schema, list, if applicable

Typical community question example:
" hmm, read that don't see anything don't know why , once consent is accepted then after that cannot redirect to url
getting 200 response from consent API instead of 302"

**Comment by aeneasr** [comment]
This has improved a lot recently, see: https://www.ory.sh/hydra/docs/reference/api
